# Generated by Django 3.1.7 on 2021-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveIntegerField(auto_created=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name Of Employee')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('post', models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('Branch-Manager', 'Branch-Manager'), ('Project-Manager', 'Project-Manager'), ('Sales-Manager', 'Sales-Manager'), ('System-Manager', 'System-Manager'), ('Back-end Developer', 'Back-end Developer'), ('Front-end Developer', 'Front-end Developer'), ('Adminstrator', 'Adminstrator')], max_length=150, verbose_name='Post')),
                ('exp', models.PositiveIntegerField(verbose_name='Experience in year')),
            ],
            options={
                'ordering': ['emp_id'],
            },
        ),
    ]
